# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irinterface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdimage',
            old_name='predictions',
            new_name='prediction1',
        ),
        migrations.AddField(
            model_name='pdimage',
            name='prediction2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdimage',
            name='prediction3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdimage',
            name='prediction4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
