# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irinterface', '0002_auto_20170728_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdimage',
            name='nickname',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
