# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irinterface', '0003_pdimage_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_src', models.FileField(upload_to='upload_networks')),
                ('weights_src', models.FileField(upload_to='upload_networks')),
            ],
        ),
        migrations.RenameField(
            model_name='pdimage',
            old_name='nickname',
            new_name='model_name',
        ),
    ]
