# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irinterface', '0004_auto_20170802_0423'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDnet',
            new_name='PdModel',
        ),
        migrations.AddField(
            model_name='pdimage',
            name='prediction',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
