# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irinterface', '0006_remove_pdmodel_weights_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdmodel',
            name='weights_src',
            field=models.FileField(default=1, upload_to='upload_networks'),
            preserve_default=False,
        ),
    ]
