# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irinterface', '0007_pdmodel_weights_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdmodel',
            name='weights_src',
        ),
    ]
